insightsfx/apps/dashboard/urls.py
from django.urls import path, include
from apps.accounts.views import EnableUser, RemoveUser, SuspendUser, ActivateUser

from . import views as v

app_name = "dashboard"

urlpatterns = [
    path("users/browse/", v.BrowseUsersView, name="list-users"),
    path("profile/", v.UserEditView, name="profile"),
    path("settings/", v.ManageSiteView, name="site-management"),
    path("settings/users/manage/edit/<int:userid>/", v.UserEditView, name="edit-user"),
    path("settings/users/manage/suspend/<int:userid>/", SuspendUser, name="suspend-user"),
    path("settings/users/manage/enable/<int:userid>/", EnableUser, name="enable-user"),
    path("settings/users/manage/remove/<int:userid>/", RemoveUser, name="remove-user"),
    path("settings/users/manage/activate/<int:userid>/", ActivateUser, name="activate-user"),
    path("list/data", v.ListData, name="list-data"),
    path("", v.IndexView, name="home"),
]

insightsfx/insightsfx/urls.py
from django.urls import path, include, reverse
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import RedirectView

urlpatterns = [
    path('accounts/', include('apps.accounts.urls', namespace="accounts")),
    path('dashboard/', include('apps.dashboard.urls', namespace="dashboard")),
    path("", RedirectView.as_view(url=settings.LOGIN_REDIRECT_URL), name="home" ),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = 'apps.core.views.page_not_found'
handler500 = 'apps.core.views.server_error'
handler403 = 'apps.core.views.permission_denied'
handler400 = 'apps.core.views.bad_request'

insightsfx/apps/dashboard/models.py
from django.db import models

# Create your models here.

insightsfx/apps/dashboard/forms.py
from crispy_forms.bootstrap import InlineRadios
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Field, Layout, Submit
from django import forms
from django.contrib.auth.forms import AdminPasswordChangeForm
from rolepermissions.checkers import has_permission

from apps.accounts.models import User
from apps.core.constants import permissions as p
from apps.accounts.roles import Subscriber, Admin

class UserForm(forms.ModelForm):

    gender = forms.ChoiceField(
        choices=User.gender_choices,
        widget = forms.RadioSelect
    )

    mobile = forms.CharField(
        label = "Mobile Number"
    )

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'gender', 'avatar', 'mobile']

    def __init__(self, user, *args, **kwargs):
        super(UserForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = "container"
        self.helper.label_class = "font-weight-bold"
        edit_sensitive_fields = True if has_permission(user, p.EDIT_USERS) else False
        
        emailField = Field('email')

        if not edit_sensitive_fields:
            emailField = Field('email', readonly=edit_sensitive_fields)
            
        self.helper.layout = Layout(
            Div(
                Field('first_name', wrapper_class='col-12 col-md-6'),
                Field('last_name', wrapper_class='col-12 col-md-6'),
                css_class="row"
            ),
            emailField,
            Field('mobile'),
            InlineRadios('gender'),
            'avatar',
        )
        self.helper.add_input(Submit('user-submit', 'Save'))

class PasswordChangeForm(AdminPasswordChangeForm):

    def __init__(self, *args, **kwargs):
        super(PasswordChangeForm, self).__init__(*args, **kwargs)
        self.fields['password1'].widget.attrs.pop("autofocus", None)

        self.helper = FormHelper()
        self.helper.label_class = "font-weight-bold"
        
        self.helper.add_input(Submit('password-change', 'Change Password'))

class RolesForm(forms.Form):

    roles = forms.MultipleChoiceField(
        choices = (
            (Subscriber.display_name, Subscriber.title),
            (Admin.display_name, Admin.title)
        )
    )

    def __init__(self, *args, **kwargs):
        super(RolesForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.label_class = "font-weight-bold"

        self.helper.add_input(Submit('change-role', 'Save Role(s)'))

class OptionsForm(forms.Form):

    site_title = forms.CharField(label = "Site Title", required=False)
    site_description = forms.CharField(label = "Site Description",required = False)
    support_email = forms.EmailField(label = "Support Email", required=False)
    site_url = forms.URLField(label = "Site URL", required=True)
    smtp_server = forms.CharField(label = "SMTP Server")
    smtp_user = forms.CharField(label = "SMPT User")
    smtp_pass = forms.CharField(label = "SMTP Password")
    smtp_port = forms.CharField(label = "SMTP Port")
    send_mails_as = forms.EmailField(label = "Send Email As")

    def __init__(self, *args, **kwargs):
        super(OptionsForm, self).__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.label_class = "font-weight-bold"
        
        self.helper.layout = Layout(
            Div(
                'site_title',
                'site_url',
                'site_description',
                'support_email',
                css_class="card my-3 my-md-5 p-3"
            ),
            Div(
                'smtp_server',
                'smtp_user',
                'smtp_pass',
                'smtp_port',
                'send_mails_as',
                css_class="card my-3 my-md-5 p-3"
            )
        )

        self.helper.add_input(Submit('save-options', 'Save Options'))
    

insightsfx/apps/dashboard/views.py
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.core.exceptions import ObjectDoesNotExist, PermissionDenied
from django.http import Http404, HttpResponse
from django.shortcuts import render
from rolepermissions.checkers import has_permission, has_role
from django.conf import settings
from rolepermissions.roles import assign_role, clear_roles, get_user_roles

from apps.accounts import roles as r
from apps.accounts.models import User
from apps.accounts.roles import Admin, Subscriber
from apps.core.constants import database_keys as dk
from apps.core.constants import permissions as p
from apps.core.utils import getOption, getOptions, setOption

from .forms import OptionsForm, PasswordChangeForm, RolesForm, UserForm
from .utils import getTableDataForUsers, GetTableData

from apps.datafetchers.models import CompareCache

# @login_required
def IndexView(request):
    if has_role(request.user, Admin):
        context = {
            "count": {
                "users": User.objects.all().count(),
            }
        }
        return render(request, "dashboard/index.html", {"data": context, "map_api_key": settings.MAPMYINDIA_API_KEY})
    else:
        context = {
            "map_api_key": settings.MAPMYINDIA_API_KEY
        }
        return render(request, "dashboard/index.html", context)
    # else:
    #     raise PermissionDenied("You are not allowed to access this page!")

@login_required
def BrowseUsersView(request):
    if has_permission(request.user, p.READ_USERS):
        enabled_columns = None
        sort_by = None
        sort_order = None
        search = None
        if request.GET.get('enabled_columns', False):
            enabled_columns = request.GET.getlist('enabled_columns')
        if request.GET.get('sort_by', False):
            sort_by = request.GET.get('sort_by')
        if request.GET.get('sort_order', False):
            sort_order = request.GET.get('sort_order')
        if request.GET.get('search', False):
            search = request.GET.get('search')

        tableData = getTableDataForUsers(enabled_columns=enabled_columns,
                                         search=search,
                                         sort_by=sort_by,
                                         sort_order=sort_order
                                         )
        return render(request, "dashboard/list.html", {"tableData": tableData})
    else:
        raise PermissionDenied("You are not allowed to List Users.")


@login_required
def UserEditView(request, userid=None):

    form = None
    user = None
    passForm = None
    rolesForm = None

    if userid == None:
        user = request.user
    elif has_permission(request.user, p.EDIT_USERS) or request.user.id == userid:
        try:
            user = User.objects.get(id=userid)
        except ObjectDoesNotExist as e:
            raise Http404("User Does Not Exist")
    else:
        raise PermissionDenied(
            "You do not have permission to edit/view this user")

    if has_permission(request.user, p.EDIT_USERS):
        roles = []
        for x in get_user_roles(user):
            roles.append(x.display_name)
        rolesForm = RolesForm({'roles': roles})

    form = UserForm(user=request.user, instance=user)
    passForm = PasswordChangeForm(user)

    if request.method == "POST":
        if 'user-submit' in request.POST:
            form = UserForm(user=request.user, data=request.POST or None,
                            files=request.FILES or None, instance=user)
            if form.is_valid():
                form.save()

        if 'password-change' in request.POST:
            passForm = PasswordChangeForm(user, request.POST or None)
            if passForm.is_valid():
                passForm.save()
                update_session_auth_hash(request, user)

        if 'change-role' in request.POST:
            rolesForm = RolesForm(request.POST or None)
            if rolesForm.is_valid():
                User().change_user_role(user, rolesForm.cleaned_data['roles'])

    return render(request, "dashboard/edit-user.html", {'form': form, 'user_context': user, 'passform': passForm, 'rolesForm': rolesForm})


@login_required
def ManageSiteView(request):
    if has_role(request.user, Admin):
        form = None
        if request.method == "POST":
            form = OptionsForm(data = request.POST, files = request.FILES or None)
            if form.is_valid():
                for data in form.cleaned_data:
                    setOption(data, form.cleaned_data[data])
        else:
            form = OptionsForm(initial=getOptions())
        return render(request, "dashboard/settings.html", {"form": form})
    else:
        raise PermissionDenied(
            "You do not have permissions to access this page!")

# @login_required
def ListData(request):
    
    tabledata = GetTableData(user=request.user)
    print('s1')
    return render(request, 'dashboard/list-single.html', {'tableData': tabledata, 'title': "Data"})

insightsfx/apps/dashboard/templates/dashboard/_base.html
{% extends '_base.html' %}
{% block title %}{% endblock %}

{% block page %}
      {% include "preloader.html" %}
      <div class="page-main">
        {% include "dashboard/components/_header.html" %}
        {% block content %}
        {% endblock %}
      </div>
      {% include "dashboard/components/_footer.html" %}
{% endblock %}

insightsfx/apps/dashboard/templates/dashboard/_base_left_sidebar.html
{% extends 'dashboard/_base.html' %}

{% block content %}
      <div class="my-3 my-md-5">
        <div class="container">
          <div class="row flex-column-reverse flex-lg-row">
            <div class="col-lg-4 sidebar" style="position: relative;">
              {% block sidebar %}{% endblock %}
            </div>
            <div class="col-lg-8">
              {% block content_block %}{% endblock %}
            </div>
          </div>
        </div>
      </div>
{% endblock %}

insightsfx/apps/dashboard/templates/dashboard/_list-table.html
{% load index %}
<style>
    .tw-80 {
        width: 80%;
        max-width: 80%;
    }
    .table-wrap {
        word-break: break-word;
        overflow: hidden;
        white-space: normal;
    }
</style>
<div class="table-responsive">
        <table class="table table-hover table-outline text-nowrap card-table">
            <thead>
                <tr>
                    {% for field in tableData.fields %}
                    <th class="{{ field.class }}">{% if field.label != "..." %}{{ field.label }}{% endif %}</th>
                    {% endfor %}
                    <th class="w-1"></th>
                </tr>
            </thead>
            <tbody>
                {% if tableData.rows|length == 0 %}
                <tr>
                    <td colspan="{{ tableData.fields|length|add:"1" }}" class="text-center text-secondary">No Entries Found</td>
                </tr>
                {% endif %}
                {% for row in tableData.rows %}
                <tr data-id="{{ row.id }}" id="row-{{ row.id }}">
                    {% for data in row.data %}
                    <td class="{% get_key_from_list tableData.fields forloop.counter0 'class' %}">
                        {% if data.type == "progress-meter" %}
                            <div class="clearfix">
                                <div class="float-left">
                                    <strong>{{ data.meta.percent }}%</strong>
                                </div>
                                {% if data.subtext %}
                                <div class="float-right">
                                    <small class="text-muted">
                                        {{ data.subtext }}
                                    </small>
                                </div>
                                {% endif %}
                            </div>
                            <div class="progress progress-xs">
                                <div class="progress-bar {% if data.meta.percent < 40 %}bg-red{% elif data.meta.percent < 70 %}bg-yellow{% else %}bg-green{% endif %}" role="progressbar" style="width:{{ data.meta.percent }}%" aria-valuenow="{{ data.meta.percent }}" aria-valuemin="0" aria-valuemax="100"></div>
                            </div>
                        {% elif data.type == "text" %}
                            <div>{{ data.text }}</div>
                            {% if data.subtext %}
                                <div class="small text-muted">{{ data.subtext }}</div>
                            {% endif %}
                        {% elif data.type == "comma-seperated-list" %}
                            <div>
                            {% for item in data.text %}
                                {{ item }}{% if not forloop.last %} ,{% endif %}
                            {% endfor %}
                            </div>
                        {% elif data.type == "link" %}
                            <div><a href="{{ data.text }}">{{ data.text|truncatechars:20 }}</a></div>
                            {% if data.subtext %}
                                <div class="small text-muted">{{ data.subtext }}</div>
                            {% endif %}
                        {% elif data.type == "currency" %}
                            <div><i class="fa fa-rupee" style="font-size: 0.85em;"></i> {{ data.text }}</div>
                        {% if data.subtext %}
                            <div class="small text-muted">{{ data.subtext }}</div>
                        {% endif %}
                        {% elif data.type == "text-inverted" %}
                            {% if data.subtext %}
                                <div class="small text-muted">{{ data.subtext }}</div>
                            {% endif %}
                            <div>{{ data.text }}</div>
                        {% elif data.type == "text-secondary" %}
                            <span class="text-muted">{{ data.text }}</span>
                        {% elif data.type == "avatar" %}
                            <div class="avatar d-block" style="background-image: url('{{ data.meta.url }}')">
                                {% if data.meta.status %}
                                <span class="avatar-status {% if data.meta.status == '1' %}bg-green{% else %}bg-red{% endif %}"></span>
                                {% endif %}
                            </div>
                        {% elif data.type == "icon" %}
                            <i class="{{ data.meta.iconclass }}"></i>
                        {% elif data.type == "boolean-indicator" %}
                            {% if data.text == True %}
                            <i class="fa fa-circle text-success"></i>
                            {% else %}
                            <i class="fa fa-circle text-danger"></i>
                            {% endif %}
                        {% endif %}
                    </td>
                    {% endfor %}
                    <td class="action-buttons text-right">
                        {% for action in row.actions %}
                        <a href="{{ action.url }}?next={{ request.path }}" class="btn btn-sm {{ action.btn_class }}">{{ action.label }}</a>
                        {% endfor %}
                        {% comment %} <a href="{% url 'dashboard:edit-user' user.id %}" class="btn btn-secondary btn-sm">Edit</a> {% endcomment %}
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

insightsfx/apps/dashboard/templates/dashboard/edit-user.html
{% extends 'dashboard/_base.html' %}
{% load crispy_forms_tags %}
{% load permission_tags %}
{% load static %}

{% block title %}Edit User{% endblock %}

{% block header_js %}
{{ form.media }}
{% endblock %}

{% block content %}
    <div class="my-3 my-md-5">
        <div class="card w-75 mx-auto">
            <div class="card-header">
                Edit User
            </div>
            <div class="card-body">
                <div class="container">
                    <div class="row">
                        <div class="col-5 mx-auto text-center">
                            <span class="avatar avatar-xxl" style="background-image:url('{% if user_context.avatar %}{{ user_context.avatar.url }}{% else %}{% static 'assets/images/avatar.png' %}{% endif %}')"></span>
                        </div>
                    </div>
                    {% if user|can:constants.permissions.EDIT_USERS %}
                    <div class="row">
                        <fieldset class="form-fieldset w-100 my-3">
                            <div class="form-row align-items-center">
                                <div class="col-12 col-sm-6 form-group align-items-center">
                                    <label class="form-label">User Id</label>
                                    <div class="form-control-plaintext">{{ user_context.id }} {% if user_context.is_active %}(Active){% else %}(Inactive){% endif %}</div>
                                </div>
                                <div class="col-12 col-sm-6 align-items-center">
                                    <label class="form-label">Member Since</label>
                                    <div class="form-control-plaintext">{{ user_context.date_joined }}</div>
                                </div>
                                <div class="col-12 col-sm-6 align-items-center">
                                    <label class="form-label">Last Login</label>
                                    <div class="form-control-plaintext">{{ user_context.last_login }}</div>
                                </div>
                                <div class="col-12 col-sm-6 align-items-center">
                                    <label class="form-label">Email Confirmed</label>
                                    <div class="form-control-plaintext">{{ user_context.email_confirmed }}</div>
                                </div>
                            </div>
                        </fieldset>
                    </div>
                    {% endif %}
                    <div class="row">
                        <fieldset class="form-fieldset w-100 my-3">
                            {% crispy form form.helper %}
                        </fieldset>
                    </div>
                    <div class="row">
                        <fieldset class="form-fieldset w-100">
                            {% crispy passform %}
                        </fieldset>
                    </div>
                    {% if rolesForm is not None %}
                    <div class="row">
                        <fieldset class="form-fieldset w-100">
                            {% crispy rolesForm %}
                        </fieldset>
                    </div>
                    {% endif %}
                    {% if user|can:constants.permissions.SUSPEND_USERS %}
                    <div class="row">
                        <fieldset class="form-fieldset w-100">
                                {% if user_context.is_active %}
                                <a href="{% if user == user_context %}#{% else %}{% url 'dashboard:suspend-user' user_context.id %}?next={{ request.path }}{% endif %}"><button class="btn btn-danger" {% if user == user_context %}disabled{% endif %}>Suspend Login</button></a>
                                {% else %}
                                <a href="{% url 'dashboard:enable-user' user_context.id %}?next={{ request.path }}"><button class="btn btn-primary">Enable Login</button></a>
                                {% endif %}
                                <a href="{% if user == user_context %}#{% else %}{% url 'dashboard:remove-user' user_context.id %}{% endif %}"><button class="btn btn-danger" {% if user == user_context %}disabled{% endif %}>Remove User</button></a>
                                {% if not user_context.email_confirmed %}
                                <a href="{% url 'dashboard:activate-user' user_context.id %}"><button class="btn btn-warning">Mark email as Confirmed</button></a>
                                {% endif %}
                        </fieldset>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

insightsfx/apps/dashboard/templates/dashboard/index-subscriber.html
{% extends "dashboard/_base.html" %}
{% load static %}
{% block title %}Home | Student Dashboard{% endblock %}

{% block content %}
<div class="my-3 my-md-5">
    <div class="container">
        <div class="page-header">
            <h1 class="page-title">
                Dashboard
            </h1>
        </div>
        <div class="row">
            <div class="col-lg-4">
                <div class="card card-profile text-center">
                    <div class="card-header" style="background-image:url('https://picsum.photos/500/300')"></div>
                    <div class="card-body">
                        <img class="card-profile-img" src="{% if user.avatar %}{{ user.avatar.url }}{% else %}{% static 'assets/images/avatar.png' %}{% endif %}">
                        <h3 class="mb-3">{{ user.get_full_name }}</h3>
                        <p class="text-secondary">{{ user.email }}</p>
                        <a class="btn btn-outline-primary btn-sm" href="{% url 'dashboard:profile' %}">Edit Profile</a>
                    </div>
                </div>
                <div class="card">
                    <a href="mailto://{{ meta.support_email }}" class="btn btn-secondary bg-teal">
                    <div class="card-body text-white text-center">
                        <span class="fa fa-support fa-2x mr-3"></span> <span class="fa-2x">Contact Support</span>
                    </div>
                    </a>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="page-header mt-0">
                    <h1 class="page-title">
                        Quick Access
                    </h1>
                </div>
                <div class="row">
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Free Forms</h3>
                                <div class="card-options">
                                    <a href="#" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
                                </div>
                            </div>
                            <div class="card-body o-auto" style="height: 20rem;">
                                {% include 'dashboard/_list-table.html' with tableData=formData.free %}
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">Paid Forms</h3>
                                <div class="card-options">
                                    <a href="#" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
                                </div>
                            </div>
                            <div class="card-body o-auto" style="height: 20rem;">
                                {% include 'dashboard/_list-table.html' with tableData=formData.paid  %}
                            </div>
                        </div>
                    </div>
                    <div class="col-12">
                        <div class="card">
                            <div class="card-header">
                                <h3 class="card-title">My Forms</h3>
                                <div class="card-options">
                                    <a href="#" class="card-options-collapse" data-toggle="card-collapse"><i class="fe fe-chevron-up"></i></a>
                                </div>
                            </div>
                            <div class="card-body o-auto" style="height: 20rem;">
                                {% include 'dashboard/_list-table.html' with tableData=formData.my %}
                            </div>
                        </div>
                    </div>    
                </div>
            </div>
        </div>
    </div>
</div>

{% endblock %}

insightsfx/apps/dashboard/templates/dashboard/list-single.html
{% extends 'dashboard/_base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
    <div class="container">
        <div class="my-3 my-md-5">
            <div class="row">
                <div class="col-12">
                    <form class="row">
                        <div class="col-12 {% if tableData.meta.filter %}col-md-6{% endif %}">
                            <div class="input-group">
                                <input type="text" class="form-control" placeholder="Type to search.." name="search" value="{{ tableData.meta.search }}">
                                <span class="input-group-append">
                                    <span class="input-group-btn"><button class="btn btn-primary" type="submit"><i class="fe fe-search"></i></button></span>
                                </span>
                            </div>
                        </div>
                        {% if tableData.meta.filter %}
                        <div class="col-12 col-md-6">
                            <div class="input-group">
                                <select class="form-control" name="filter">
                                    <option value="">Filter By </option>
                                    {% for option in tableData.meta.filter %}
                                    <option value="{{ option.value }}" {% if option.value == tableData.meta.filter_by %}selected{% endif %}>{{ option.label }}</option>
                                    {% endfor %}
                                </select>
                                <span class="input-group-append">
                                    <span class="input-group-btn"><button class="btn btn-warning" type="submit"><i class="fe fe-filter"></i></button></span>
                                </span>
                            </div>
                        </div>
                        {% endif %}
                    </form>
                </div>
                <div class="col-12 my-3 my-md-5">
                    <div class="card card-table">
                        {% include 'dashboard/_list-table.html' %}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

insightsfx/apps/dashboard/templates/dashboard/settings.html
{% extends 'dashboard/_base.html' %}
{% load crispy_forms_tags %}
{% block title %}Settings{% endblock %}

{% block content %}
<div class="container">
    <div class="page-header">
        <h3 class="page-title"><i class="fe fe-settings"></i> Settings</h3>
    </div>
    {% crispy form %}
</div>
{% endblock %}